version: "3.7"

services: 
  socket:
    image: weni-websocket
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    environment: 
      - WWC_PORT=${WWC_PORT:-8081}
      - WWC_LOG_LEVEL=${WWC_LOG_LEVEL:-CHANGE_ME}
      - WWC_S3_ENDPOINT=${WWC_S3_ENDPOINT:-CHANGE_ME}
      - WWC_S3_REGION=${WWC_S3_REGION:-CHANGE_ME}
      - WWC_S3_BUCKET=${WWC_S3_BUCKET:-CHANGE_ME}
      - WWC_S3_ACCESS_KEY=${WWC_S3_ACCESS_KEY:-CHANGE_ME}
      - WWC_S3_SECRET_KEY=${WWC_S3_SECRET_KEY:-CHANGE_ME}
    ports:
      - 8081:8081
    depends_on:
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.1.5
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
     - grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    

